version: '3'
services:
  scientistapp:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 3306
    volumes:
     - .:/src/app/
     - /src/app/node_modules/